name: Deepak Chopra
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7328701531514525
title: Deepak Chopra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.04018618771806359
  saturation: 0.2745522321201861
  rhythmicContrast: 0.5932446282822639
purpose: []
